 <!-- <div class="row">
        <div class="col-xs-12">
            <a href="/promotions">
                <picture class="promotion-image">
                    <source srcset="/media/responsive_images/Goldburgh_Mobile_Promotion.jpg" media="(max-width: 768px)">
                    <img class="lazyload" 
                    style="width: 100%;"
                    alt="Get a free Hat & Pom when you buy any goldburgh product over $299"
                    data-src="/media/responsive_images/Goldburgh_Desktop_Promotion.jpg" 
                    src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="> 
                </picture>
            </a>
        </div>
    </div>
    <br/>
    <br/> -->