<div class="row">

  <div class="col-sm-3 col-3">
    <div class="thumbnail">
      <picture>
        <img class="lazyload" alt="Breathable" data-src="/media/swissup/argento/luxury/images/pics/Toque-Symbols-Breathable[2].jpg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
      </picture>
    </div>
    <span>Breathable</span>
  </div>

  <div class="col-sm-3 col-3">
    <div class="thumbnail">
      <picture>
        <img class="lazyload" alt="Breathable" data-src="/media/swissup/argento/luxury/images/pics/Toque-Symbols-All-Mountain[2].jpg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
      </picture>
    </div>
    <span>All Mountain</span>
  </div>

  <div class="col-sm-3 col-3">
    <div class="thumbnail">
      <picture>
        <img class="lazyload" alt="Breathable" data-src="/media/swissup/argento/luxury/images/pics/Toque-Symbols-Insulates[2].jpg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
      </picture>
    </div>
    <span>Insulates</span>
  </div>

  <div class="col-sm-3 col-3">
    <div class="thumbnail">
      <picture>
        <img class="lazyload" alt="Interchangeable" data-src="/media/swissup/argento/luxury/images/pics/Toque-Symbols-Interchangable-Pom-Pom[2].jpg" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
      </picture>
    </div>
    <span>Interchangeable</span>
  </div>
</div>

<div>
  <h4>Free Shipping Over $125</h4>
</div>