<?php
/**
* Product media data template
*
* @var $block \Magento\Catalog\Block\Product\View
*/
?>
    <a class="product-social-sharing" data-type="facebook" data-name="<?= $block->getProduct()->getName()?>"
       href="http://www.facebook.com/sharer.php?u=<?= $block->getProduct()->getProductUrl() ?>" target="_blank">
        <i class="fab fa-2x fa-facebook-square"></i></a>
    <a class="product-social-sharing" data-type="pinterest"  data-name="<?= $block->getProduct()->getName()?>"
       href="http://pinterest.com/pin/create/button/?url=<?= $block->getProduct()->getProductUrl() ?>" target="_blank">
        <i class="fab fa-2x fa-pinterest-square"></i></a>
    <a class="product-social-sharing" data-type="twitter"  data-name="<?= $block->getProduct()->getName()?>"
       href="http://twitter.com/share?url=<?= $block->getProduct()->getProductUrl()?>&text=<?= $block->getProduct()->getName()?>"
       target="_blank"><i class="fab fa-2x fa-twitter-square"></i></a>
    <a class="product-social-sharing" data-type="linkedin"  data-name="<?= $block->getProduct()->getName()?>"
       href="https://www.linkedin.com/shareArticle?mini=true&url=<?= $block->getProduct()->getProductUrl()?>&t=<?= $block->getProduct()->getName()?>"
       onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
       target="_blank" title="Share on Linkedin"><i class="fab fa-2x fa-linkedin-square" aria-hidden="true"></i></a>

