<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Act\MainMenu\Block\TopMenu
 */

// $writer = new \Zend\Log\Writer\Stream(BP . '/var/log/mainmenu.log');
// $logger = new \Zend\Log\Logger();
// $logger->addWriter($writer);
$hats = $block->getHats();
$poms = $block->getPoms();
$goldbergh = $block->getGoldbergh();
// $logger->debug($poms);


?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <!--    <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/boxing-day" class="level-top ui-corner-all" id="ui-id-1" tabindex="-1" role="menuitem"><span>Boxing Day</span></a></li> -->
        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/hats" class="level-top ui-corner-all" id="ui-id-1" tabindex="-1" role="menuitem"><span>Hats</span></a>
            <?php if(!empty($hats)): ?>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 50.4844px; left: 0.453125px;" aria-hidden="true">
                <li class="level1 nav-2-3 category-item first last ui-menu-item" role="presentation"><a href="/hats" target="_self" id="ui-id-7" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Shop All</span></a></li>
                <?php foreach($hats as $cat): ?>
                    <li class="level1 nav-2-1 category-item first last ui-menu-item" role="presentation"><a href="<?php echo $cat['url'] ?>" target="_self" id="ui-id-<?php echo $cat['id'] ?>" class="ui-corner-all" tabindex="-1" role="menuitem"><span><?php echo $cat['name'] ?></span></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>

        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/poms" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem"><span>Poms</span></a>
            <?php if(!empty($poms)): ?>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 50.4844px; left: 0.453125px;" aria-hidden="true">
                <li class="level1 nav-2-3 category-item first last ui-menu-item" role="presentation"><a href="/poms" target="_self" id="ui-id-7" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Shop All</span></a></li>
                <?php foreach($poms as $cat): ?>
                    <li class="level1 nav-2-1 category-item first last ui-menu-item" role="presentation"><a href="<?php echo $cat['url'] ?>" target="_self" id="ui-id-<?php echo $cat['id'] ?>" class="ui-corner-all" tabindex="-1" role="menuitem"><span><?php echo $cat['name'] ?></span></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>

        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation">
            <a href="<?= $block->getUrl('individual-hats/popular-pombos') ?>" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1"
               role="menuitem"><span>Pombos</span></a>
        </li>

        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/build-your-own" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem"><span>Build Your Own</span></a></li>
        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/goldbergh" class="level-top ui-corner-all" id="ui-id-2" tabindex="-1" role="menuitem"><span>Goldbergh</span></a>
            <?php if(!empty($goldbergh)): ?>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 50.4844px; left: 0.453125px;" aria-hidden="true">
                <?php foreach($goldbergh as $cat): ?>
                    <li class="level1 nav-2-1 category-item first last ui-menu-item" role="presentation"><a href="<?php echo $cat['url'] ?>" target="_self" id="ui-id-<?php echo $cat['id'] ?>" class="ui-corner-all" tabindex="-1" role="menuitem"><span><?php echo $cat['name'] ?></span></a></li>
                <?php endforeach; ?>
            </ul>
            <?php endif; ?>
        </li>
        <li class="level0 nav-2 category-item level-top parent ui-menu-item" role="presentation"><a class="level-top ui-corner-all" aria-haspopup="true" id="ui-id-4" tabindex="-1" role="menuitem"><span class="ui-menu-icon ui-icon ui-icon-carat-1-e"></span><span>Hat Style Guide</span></a>
            <ul class="level0 submenu ui-menu ui-widget ui-widget-content ui-corner-all" role="menu" aria-expanded="false" style="display: none; top: 50.4844px; left: 0.453125px;" aria-hidden="true">
                <li class="level1 nav-2-1 category-item first last ui-menu-item" role="presentation"><a href="/hat-styles" target="_blank" id="ui-id-5" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Hat Styles</span></a></li>
                <li class="level1 nav-2-2 category-item first last ui-menu-item" role="presentation"><a href="/pom-styles" target="_blank" id="ui-id-6" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Pom Styles</span></a></li>
                <li class="level1 nav-2-3 category-item first last ui-menu-item" role="presentation"><a href="/pom-size-guide" target="_blank" id="ui-id-7" class="ui-corner-all" tabindex="-1" role="menuitem"><span>Pom Size Guide</span></a></li>
            </ul>
        </li>
        <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/extras" class="level-top ui-corner-all" id="ui-id-8" tabindex="-1" role="menuitem"><span>Accessories</span></a></li>
        <li class="level0 nav-5 category-item last level-top ui-menu-item" role="presentation"><a href="/sale" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span>Sale</span></a></li>
        <!-- <li class="level0 nav-4 category-item last level-top ui-menu-item" role="presentation"><a href="/blog" class="level-top ui-corner-all" id="ui-id-9" tabindex="-1" role="menuitem"><span>Blog</span></a></li> -->

    </ul>
</nav>
