<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php /* @var $block \Magento\Catalog\Block\Product\View\Options\Type\Select */ ?>
<?php
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
?>
<div class="field active<?= /* @escapeNotVerified */ $class ?>">
    <div class="collapsible" style="display:block; cursor:pointer;">
    <label class="label" for="select_<?= /* @escapeNotVerified */ $_option->getId() ?>">
        <span><?= $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    </div>
    <div class="control">
        <?php $optionHtml = $block->getValuesHtml();?>
        <?= (strpos($optionHtml, 'hidden')!==false) ? str_replace(['hidden','<select'], ['','<select style="opacity:0;padding:0;height:0" data-limit="'.$_option->getSelectionLimitTo().'"'], $optionHtml) : $optionHtml ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_RADIO || $_option->getType() == \Magento\Catalog\Api\Data\ProductCustomOptionInterface::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?= /* @escapeNotVerified */ $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</div>


