<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_DependentCustomOption
 * @author     Extension Team
 * @copyright  Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */

// @codingStandardsIgnoreFile

/**
 * Date options block
 *
 * @var \Bss\DependentCustomOption\Block\Render\DependentControl $block
 */
?> 

<?php
$option = $block->getOption();
$moduleConfig = $block->getConfigHelper();
?>
<?php if ($moduleConfig->isModuleEnable() && $block->getDependData()) : ?>
    <script type="text/x-magento-init">
        {
            "#bss_options_<?php echo $option->getId() ?>": {
                "bss_dco_control": {
                	"optionType": "<?php echo $option->getType() ?>",
                    "optionId": "<?php echo $option->getId() ?>",
                    "dcoData": <?php echo $block->getDependData() ?>,
                    "childrenDisplay": "<?php echo $moduleConfig->getChildrenDisplay() ?>",
                    "multipleParentValue": "<?php echo $moduleConfig->getMultipleParentValue() ?>",
                    "dcoRequire": "<?php echo $option->getData('bss_dco_require') ?>"
                }
            }
        }
    </script>
<?php endif;?> 