<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": {"fullscreenzoom":"20","top":"","left":"","width":"","height":"","eventType":"hover","enabled":"false","mode":"outside"},
                "data": [],
                "options": {"nav":"thumbs","allowfullscreen":true,"showCaption":false,"width":700,"thumbwidth":88,"navdir":"vertical","thumbheight":110,"height":700,"loop":true,"keyboard":true,"navtype":"slides","navarrows":true,"transitionduration":"300","transition":"crossfade"},
                "fullscreen": {"nav":"thumbs","thumbwidth":230,"navdir":"vertical","navarrows":false,"arrows":false,"showCaption":false,"thumbheight":"100%"},
                "breakpoints": {"mobile":{"conditions":{"max-width":"767px"},"options":{"options":{"nav":"dots","navdir":"horizontal","transition":{"effect":"slide","duration":"300"},"allowfullscreen":true}}}}            }
        }
    }
</script>


