<!-- The homepage banner is rendered above this -->

<!-- Start of Tabs -->

<div class="container">
    <div class="linktabs">
        <div class="tab">
            <a href="https://lindoffur.simplybook.me/v2/#book/service/1/count/1/" target="_blank">Book IN-Store Appt</a>
        </div>
        <div class="tab">
            <a href="<?= $block->getUrl('build-your-own') ?>">Book Online Consult</a>
        </div>
        <div class="tab">
            <a href="/where-to-buy" target="_blank">Where To Buy</a>
        </div>
        <div class="tab">
            <a href="/gift-cards" target="_blank">Gift Cards</a>
        </div>
        <div class="tab">
            <a href="/new-member-sign-up" target="_blank">Become a Member</a>
        </div>
    </div>
</div>

<!-- End of Tabs -->


<!-- Below the Hero Image -->

<div class="expanded-feature-bg">

    <!-- Main Product -->
    <!-- <div class="row">
        <div class="col-xs-12">
            <a href="/promotions">
                <picture class="promotion-image">
                    <source srcset="/media/responsive_images/Goldburgh_Mobile_Promotion.jpg" media="(max-width: 768px)">
                    <img class="lazyload" 
                    style="width: 100%;"
                    alt="Get a free Hat & Pom when you buy any goldburgh product over $299"
                    data-src="/media/responsive_images/Goldburgh_Desktop_Promotion.jpg" 
                    src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="> 
                </picture>
            </a>
        </div>
    </div> -->

    <div class="container product-feature">
        <div class="row">
            <div class="col-sm-12 col-md-4 col-md-offset-4">
                <a class="no-link" href="/build-your-own">

                    <picture class="featured-image">
                        <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/static/frontend/Local/luxurysubtheme/en_US/images/lindof-BuildYourown.jpg" class="lazyload" alt="Product Image" />
                    </picture>
                </a>
                <a href="/build-your-own">
                    <h3>Interchangeable Pom Pom Hats</h3>
                </a>
                <div class="row icon-row">
                    <hr class="col-sm-4">
                    <div class="col-sm-4">
                        <picture>
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/static/frontend/Local/luxurysubtheme/en_US/images/beanie.svg" class="lazyload hat-icon" alt="beanie icon" />
                        </picture>
                    </div>
                    <hr class="col-sm-4">
                </div>
                <button onclick="window.location.href = '/build-your-own';" type="button">Build Your Own</button>
            </div>

            <div class="col-sm-12 col-md-3 col-md-offset-1 featured">
                <h5>Features</h5>
                <p>100% Merino Wool<br>
                    Interchangeable Real and Faux Fur Poms<br>
                    Over 40 Colours to suit your style
                </p>
                <h5>From $99.99</h5>
                <a href="/build-your-own">Learn More</a>
            </div>

        </div>
    </div>

</div>

<div class="jumbotron wrapper">

    <!-- Categories -->


    <!--    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-4 category-image">
                <a href="/toques" class="category-text">Hats</a>
            </div>
            <div class="col-sm-12 col-md-4 category-image">
                <a href="/vests" class="category-text">Vests</a>
            </div>
            <div class="col-sm-12 col-md-4 category-image">
                <a href="/accessories" class="category-text">Accessories</a>
            </div>
        </div>
    </div>

-->


    <!-- 50/50 Grid -->


    <div class="container mrgn-btm">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <picture>
                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="<?= $block->getViewFileUrl('images/Fall_Hats.jpg') ?>" class="lazyload" alt="Girls wearing beanies at the ski hill" />
                </picture>
            </div>
            <div class="col-sm-12 col-md-6 block-text">
                <h2>Our<br>Hats</h2>
                <div class="row icon-row">
                    <hr class="col-sm-4">
                    <div class="col-sm-4">
                        <picture>
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/static/frontend/Local/luxurysubtheme/en_US/images/beanie.svg" class="lazyload hat-icon" alt="beanie icon" />
                        </picture>
                    </div>
                    <hr class="col-sm-4">
                </div>
                <p>Featuring the softest wool for ultimate comfort, performance and style.</p>
                <button onclick="window.location.href = '/hats';" type="button">Shop Hats</button>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-6 col-md-push-6">
                <picture>
                    <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/static/frontend/Local/luxurysubtheme/en_US/images/Fall_Pom.jpg" class="lazyload" alt="Child wearing beanie image" />
                </picture>
            </div>
            <div class="col-sm-12 col-md-6 col-md-pull-6 block-text">
                <h2>Our<br>Poms</h2>
                <div class="row icon-row">
                    <hr class="col-sm-4">
                    <div class="col-sm-4">
                        <picture>
                            <img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="/static/frontend/Local/luxurysubtheme/en_US/images/beanie.svg" class="lazyload hat-icon" alt="beanie icon" />
                        </picture>
                    </div>
                    <hr class="col-sm-4">

                </div>
                <p>The wispy tips and natural detail define these luxurious Poms.</p>
                <button onclick="window.location.href = '/poms';" type="button">Shop Poms</button>
            </div>
        </div>

    </div>

    <!-- Picture Grid -->


    <!--    <div class="container mrgn-btm image-grid">
        <div class="row">
            <div class="col-md-12">
                <h2>Own Your Style</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-3 col-md-offset-1">
                <picture>
                        <img
                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                        data-src="/static/frontend/Local/luxurysubtheme/en_US/images/image_grid_1.jpg"
                        class="lazyload"
                        alt="Black fur pom pom with brown toque" />
                </picture>
            </div>
            <div class="col-sm-12 col-md-7">
                <div class="col-sm-12">
                    <picture>
                        <img
                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                        data-src="/static/frontend/Local/luxurysubtheme/en_US/images/image_grid_2.jpg"
                        class="lazyload"
                        alt="Purple fur pom pom with purple toque" />
                    </picture>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <picture>
                        <img
                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                        data-src="/static/frontend/Local/luxurysubtheme/en_US/images/Image_Grid_3.jpg"
                        class="lazyload"
                        alt="Tan fur pom pom with green hat" />
                        </picture>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <picture>
                        <img
                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                        data-src="/static/frontend/Local/luxurysubtheme/en_US/images/image_grid_4.jpg"
                        class="lazyload"
                        alt="Black fur pom pom with grey toque" />
                        </picture>
                    </div>
                </div>
            </div>
        </div>
    </div>
-->
    <!-- Full Width Banner -->

    <div class="container">
        <div class="row fluid-parallax mrgn-btm">
            <div class="col-sm-12 text-parallax">
                <h2>Build Your Style</h2>
                <h4>Select a hat and pom from over 300 choices</h4>
                <button onclick="window.location.href = '/build-your-own';" type="button">Build Your Own</button>
            </div>
        </div>
    </div>
</div>